version: 1.0.{build}
configuration: Release
clone_depth: 50
install:
- cmd: >-
    git submodule update --init --recursive

    xcopy .\SteamAuthPackagesOverride.config SteamAuth\SteamAuth\packages.config /y
before_build:
- cmd: >-
    nuget restore "SteamAuth\SteamAuth\SteamAuth.sln"

    msbuild "SteamAuth\SteamAuth\SteamAuth.sln" /m /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
build:
  project: SteamBot.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: >-
    copy NUL > Bin\Release\zzz.update
artifacts:
- path: Bin\Release\*
  name: Release
deploy:
- provider: FTP
  host: lamia.geit.uk
  protocol: ftp
  username: puff
  password:
    secure: gw1w12yvTDsgUfpW/go6bT4IqEVekYeOf3veoHSKZYE=
  artifact: Release
  beta: true
  debug: true
  on:
    branch: master
